capstone/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tv.urls"))
]

tv/urls.py
from django.urls import path

from . import views

app_name = "tv"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("search", views.search, name="search"),
    path("show/<int:show_id>/<str:show_name>", views.show, name="show"),

    # API routes
    path("track/<int:show_id>", views.track, name="track"),
    path("untrack/<int:show_id>", views.untrack, name="untrack"),

]

tv/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class Show(models.Model):

    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"


class User(AbstractUser):

    shows = models.ManyToManyField(Show, blank=True, related_name="trackers")

    def __str__(self):
        return f"{self.username}"

tv/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from . import util
from .models import User, Show

def index(request):

    if request.user.is_authenticated:
        tracks = Show.objects.filter(trackers=request.user)
        ids = tracks.values_list("id", flat=True)
        shows = [util.get_show(tracked_show.id) for tracked_show in tracks]
    else:
        shows = []
        ids = []
    return render(request, "tv/index.html", {
        "shows": shows,
        "ids": ids
    })

def search(request):
    query = request.GET.get("q")
    shows = util.get_shows(query)
    if request.user.is_authenticated:
        tracks = Show.objects.filter(trackers=request.user)
        ids = tracks.values_list("id", flat=True)
    else:
        ids = []
    return render(request, "tv/search.html", {
        "shows": shows,
        "ids": ids
    })


def show(request, show_id, show_name):
    show = util.get_show(show_id)
    if request.user.is_authenticated:
        tracks = Show.objects.filter(trackers=request.user)
        ids = tracks.values_list("id", flat=True)
    else:
        ids = []
    return render(request, "tv/show.html", {
        "show": show,
        "ids": ids
    })


@csrf_exempt
@login_required
def track(request, show_id):

    if request.method == "POST":

        try:
            show = util.get_show(show_id)
        except AttributeError:
            return JsonResponse({"error": "Show to track not found."}, status=404)
        try:
            tracked_show = Show.objects.get(pk=show_id)
        except Show.DoesNotExist:
            tracked_show = Show.objects.create(id=show["id"], name=show["name"])

        request.user.shows.add(tracked_show)
        request.user.save()

        return HttpResponse(status=204)

    else:
        return JsonResponse({
            "error": "POST request required."
        }, status=400)


@csrf_exempt
@login_required
def untrack(request, show_id):

    try:
        tracked_show = Show.objects.get(pk=show_id)
    except Show.DoesNotExist:
        return JsonResponse({"error": "Show to untrack not found."}, status=404)

    if request.method == "POST":
        print(request.user.shows)
        request.user.shows.remove(tracked_show)
        request.user.save()
        return HttpResponse(status=204)

    else:
        return JsonResponse({
            "error": "POST request required."
        }, status=400)    


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("tv:index"))
        else:
            return render(request, "tv/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "tv/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("tv:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "tv/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "tv/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("tv:index"))
    else:
        return render(request, "tv/register.html")

tv/templates/tv/index.html
{% extends "tv/layout.html" %}
{% load static %}

{% block body %}

    <h2>My Shows</h2>

    {% if user.is_authenticated %}

        {% if shows %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" id="navSortFilterButton"
                        data-toggle="collapse" data-target="#navSortFilter">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navSortFilter">
                    <h4>Sort by:</h4>
                    <ul class="navbar-nav">
                        <li class="nav-item sort">
                            <button class="btn btn-primary sort-button" id="name-sort">Name
                                <span class="up-arrow">&#8679;</span>
                                <span class="down-arrow">&#8681;</span>
                            </button>
                        </li>
                        <li class="nav-item sort">
                            <button class="btn btn-primary sort-button" id="channel-sort">Channel
                                <span class="up-arrow">&#8679;</span>
                                <span class="down-arrow">&#8681;</span>
                            </button>
                        </li>
                        <li class="nav-item sort">
                            <button class="btn btn-primary sort-button" id="airdate-sort">Most Recent Episode
                                <span class="up-arrow">&#8679;</span>
                                <span class="down-arrow">&#8681;</span>
                            </button>
                        </li>
                    </ul>

                    <div class="vertical-divider"></div>

                    <h4>Filter by:</h4>
                    <ul class="navbar-nav filters">
                        <li class="nav-item filter-group">
                            <h6>Channel</h6>
                            <div id="channel-filters" class="form-group"></div>
                        </li>
                        <li class="nav-item filter-group">
                            <h6>Status</h6>
                            <div id="status-filters" class="form-group"></div>
                        </li>
                    </li>
                    </ul>
                </div>
            </nav>
        {% endif %}

        <div id="show-summaries">
            {% for show in shows %}
                {% include 'tv/showsummary.html' with show=show user=user %}
            {% empty %}
                <p>You are currently tracking no shows. Search for shows to track.</p>
            {% endfor %}
        </div>

    {% else %}
        <p>Log in to see the shows you are tracking, or register and begin searching for shows to track.</p>
    {% endif  %}

{% endblock %}

{% block script %}
<script type="module" src="{% static 'tv/track.js' %}"></script>
<script type="module" src="{% static 'tv/sort.js' %}"></script>
<script type="module" src="{% static 'tv/filter.js' %}"></script>
<script type="module" src="{% static 'tv/menu.js' %}"></script>
{% endblock %}

{% load static %}

tv/templates/tv/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}TV Tracker{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'tv/styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% block script %}
        {% endblock %}
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

            <a class="navbar-brand" href="{% url 'tv:index' %}">TV Tracker</a>

            {% if user.is_authenticated %}
                <span class="navbar-text float-right"><strong>{{ user.username }}</strong></span>
            {% endif %}

            <div class="container-fluid">
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tv:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tv:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tv:register' %}">Register</a>
                    </li>
                {% endif %}
                    <li class="nav-item">
                        <form class="form-inline my-2 my-lg-0 navbar-right" action="{% url 'tv:search' %}">
                            <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search for shows" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </li>
              </ul>
            </div>
        </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

tv/templates/tv/login.html
{% extends "tv/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'tv:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'tv:register' %}">Register here.</a>

{% endblock %}

tv/templates/tv/register.html
{% extends "tv/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'tv:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'tv:login' %}">Log In here.</a>

{% endblock %}

tv/templates/tv/search.html
{% extends "tv/layout.html" %}
{% load static %}

{% block body %}

    <h2>Search Results</h2>
    {% for show in shows %}
        {% include 'tv/showsummary.html' with show=show user=user %}
    {% empty %}
        <p>No shows matching that query found.</p>
    {% endfor %}

{% endblock %}

{% block script %}
    <script type="module" src="{% static 'tv/track.js' %}"></script>
{% endblock %}

tv/templates/tv/show.html
{% extends "tv/layout.html" %}
{% load static %}

{% block body %}
    <h2>{{ show.name }}</h2>
    <div class="container float-left show" id="show-{{ show.id }}">
        <div class="row">
            {% if show.image %}
                <div class="col-md-4">
                    <img src="{{ show.image }}" alt="{{ show.name }}">
                </div>
            {% endif %}
            <div class="col-md-4">
                {{ show.summary|safe }}
            </div>
            <div class="col-md-4">
                <ul class="show-info">
                    <li><strong>Channel:</strong> {{ show.channel }}</li>
                    <li><strong>Premiered:</strong> {{ show.premiered }}</li>
                    <li><strong>Most Recent Episode:</strong> {{ show.mostrecentairdate }}</li>
                    <li><strong>URL:</strong> <a href="{{ show.url }}">{{ show.url }}</a></li>
                    <li><strong>Status:</strong> {{ show.status }}</li>
                </ul>
            </div>
        </div>

        <div class="row">
            {% include 'tv/track.html' with show=show user=user %}
        </div>
    </div>


{% endblock %}

{% block script %}
    <script type="module" src="{% static 'tv/track.js' %}"></script>
{% endblock %}

{% load static %}

tv/templates/tv/showsummary.html
<div class="container-sm show-summary" id="show-{{ show.id }}">
    <div class="row">
        <div class="col-lg-10 col-sm-8">
            <h3>
                <a class="show-name" href="{% url 'tv:show' show.id show.name|lower|slugify %}">{{ show.name }}</a>
                {% if show.channel %}
                    <span> &mdash; </span><span class="show-channel">{{ show.channel }}</span>
                {% endif %}

                {% if show.startyear and show.endyear %}
                    {% if show.startyear == show.endyear %}
                        <span> ({{ show.startyear }})</span>
                    {% else %}
                        <span> ({{ show.startyear }}&ndash;{{ show.endyear }})</span>
                    {% endif %}
                {% elif show.startyear and not show.endyear %}
                    <span> ({{ show.startyear }}&ndash;)</span>
                {% endif %}
            </h3>
            <p>
                {% if show.mostrecentairdate %}
                    <span><strong>Most Recent Episode: </strong></span><span class="show-airdate">{{ show.mostrecentairdate }}</span>
                {% endif %}
                {% if show.status %}
                    <span> | <strong>Status: </strong></span><span class="show-status">{{ show.status }}</span>
                {% endif %}
            </p>
        </div>

        {% include 'tv/track.html' with show=show user=user %}

    </div>
</div>

tv/templates/tv/track.html
{% if user.is_authenticated %}
    <div class="col-lg-2 col-sm-4">
        <button class="btn btn-secondary track-button">
            {% if show.id in ids %}
                Untrack
            {% else %}
                Track
            {% endif %}
        </button>
    </div>
{% endif %}